<?php
error_log("\n\n");
error_log("------------------- GLOBALS\n\n");
error_log(print_r($GLOBALS, true));
error_log("\n\n");
error_log("------------------- END GLOBALS\n\n");
error_log("\n\n");
error_log("---------- START _REQUEST\n\n");
error_log("\n\n");
error_log(print_r($_REQUEST,true));
error_log("---------- STOP _REQUEST\n\n");
error_log("\n\n");
error_log("---------- START _POST\n\n");
error_log("\n\n");
error_log(print_r($_POST,true));
error_log("\n\n");
error_log("---------- STOP _POST\n\n");
error_log("\n\n");
error_log("---------- START _GET\n\n");
error_log("\n\n");
error_log(print_r($_GET,true));
error_log("\n\n");
error_log("---------- STOP _GET\n\n");
error_log("\n\n");
